# 环境配置
server:
  servlet:
    # 上下文配置
    context-path: /
  # tomcat 配置
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    max-swallow-size: -1
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

# spring 配置
spring:
  # 激活配置
  profiles:
    active: dev
  # 应用配置
  application:
    name: i2f-app
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 300MB
      # 设置总上传的文件大小
      max-request-size: 2048MB
  # 热部署
  devtools:
    restart:
      # 热部署开关
      enabled: true
      # 排除监听改变的路径
      exclude: logs/**
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
  aop:
    proxy-target-class: true
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /res/**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: UserHikariCP


mybatis:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
    - classpath*:com/i2f/**/mapper/xml/*Mapper.xml
    - classpath*:com/i2f/**/dao/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true

# pagehelper 配置
pagehelper:
  reasonable: false
  row-bounds-with-count: true
  helper-dialect: mysql

# 日志配置
logging:
  level:
    root: info

feign:
  client:
    config:
      default:
        logger-level: full
        connect-timeout: 6000
        read-timeout: 6000

# redis 配置
i2f:
  springboot:
    config:
      redis:
        enable: true
        # 是否使用lettuce工厂穿件redisTemplate，默认使用
        enable-lettuce-factory: false
        # 指定使用Jackson序列化时用的日期时间格式
        date-format: yyyy-MM-dd HH:mm:ss SSS
        redis:
          cache:
            enable: true
        # 是否配置lettuce的自动心跳检测
        # 解决lettuce客户端因为TCP重传超时不可用的问题，另一种方式是maven替换lettuce为jedis
        lettuce:
          heart-beat:
            enable: false
            init-delay-seconds: 30
            rate-seconds: 30

      # mybatis 配置
      mybatis:
        enable: true
        # 开启拦截器插件总开关
        interceptor:
          enable: true
          # 开启自动转换驼峰插件，在需要开启驼峰转换的mapper接口方法上加MybatisCamel注解即可
          camel-key-pre-process:
            enable: true
          # 开启执行SQL的日志插件，在需要开启日志的mapper接口方法上加MybatisLog注解即可
          sql-log:
            enable: true
      # 多数据源配置
      datasource:
        enable: true
      secure:
        # 是否开启
        enable: true
        # 默认的安全控制策略，也就是当注解和白名单都未配置时的策略模式，默认关闭
        defaultControl:
          # 入站是否安全
          in: true
          # 出站是否安全
          out: true
        # 白名单配置列表项，符合ant-match模式
        whiteList:
          # 进出站都忽略的列表清单
          bothPattens:
            - /api/sys/file/**
            - /secure/key
          # 进站忽略的列表清单
          inPattens:
            - /api/sys/file/upload/**
          # 出站忽略的列表清单
          outPattens:
            - /api/sys/file/download/**
