# 应用配置
server:
  # 端口配置
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://47.92.88.61:3306/i2f_proj?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ltb12315
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis 配置
  redis:
    database: 0
    host: 47.92.88.61
    password: ltb12315
    port: 6379
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 1     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
  security:
    user:
      name: root
      password: ltb12315
      roles:
        - root

i2f:
  springboot:
    file:
      downloadHost: localhost
    config:
      # 多数据源配置
      datasource:
        # 必须的主数据源 master，如果没有明确指定主数据源，将使用springdatasource默认的单数据源，作为主数据源
        # 这里，就是用spring.datasource的数据源作为主数据源
        multiply:
          # 这里定义了一个叫做common的数据源
          common:
            driver: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://47.92.88.61:3306/common_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
            username: root
            password: ltb12315
      # security 配置
      security:
        # 是否开启springsecurity功能，默认开启
        enable: true
        # session 管理模式，默认无状态
        session-creation-policy: STATELESS
        # 忽略访问名单，默认无
        ignore-list: /secure/**,/sys/entrance/**,/verifycode/**,/api/rtmp/**
        # 匿名访问名单，默认无
        anonymous-list: /actuator/**
        # 完全开放访问名单，默认无
        permit-all-list: /**/*.html
        # 完全开放仅GET方式访问的资源，默认页面文件
        static-resource-list: /**/*.html,/**/*.css,/**/*.js,/**/*.png,/**/*.jpg,/**/*.jpeg
        # 是否开启csrf,默认关闭
        csrf:
          enable: false
        # 是否开启cors,默认开启
        cors:
          enable: true
        # 是否开启表单登录，默认开启
        form-login:
          enable: true
        # 是否开启http-basic,默认关闭
        http-basic:
          enable: false
        # 是否开启无权限403响应返回，默认开启
        enable-exception-handler: true
        # 是否支持json-post方式登录，默认支持
        login-json:
          enable: true
        # 登录请求的path,默认/login
        login-url: /login
        # 登录请求的用户名属性名，默认username
        login-username: username
        # 登录请求的用户密码属性名，默认password
        login-password: password
        # 是否开启单点登录，在默认实现中生效，默认开启单点登录
        login-single:
          enable: true
        # 默认的实现中的用户名密码配置,可以配置多个，每一个用分号分隔
        default-impl-login:
          users: admin/admin=ROLE_admin,sys:config:manage;user/123456
